[2024-10-30T23:05:14.774+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T23:05:15.606+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T23:00:00+00:00 [queued]>
[2024-10-30T23:05:15.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T23:00:00+00:00 [queued]>
[2024-10-30T23:05:15.709+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T23:05:15.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sensor_data_generator> on 2024-10-30 23:00:00+00:00
[2024-10-30T23:05:15.905+0000] {standard_task_runner.py:64} INFO - Started process 2137 to run task
[2024-10-30T23:05:15.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_data', 'sensor_data_generator', 'scheduled__2024-10-30T23:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/sensor_***.py', '--cfg-path', '/tmp/tmpogfvhikv']
[2024-10-30T23:05:15.956+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask sensor_data_generator
[2024-10-30T23:05:16.505+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data.sensor_data_generator scheduled__2024-10-30T23:00:00+00:00 [running]> on host 5d793f8b441e
[2024-10-30T23:05:17.614+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bich Ly' AIRFLOW_CTX_DAG_ID='sensor_data' AIRFLOW_CTX_TASK_ID='sensor_data_generator' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-30T23:00:00+00:00'
[2024-10-30T23:05:17.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T23:05:18.050+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.051+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.053+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.083+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.083+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.122+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.123+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.123+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.159+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.160+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.194+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.199+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.200+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.234+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.248+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.291+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.292+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.293+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.468+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.470+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.530+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.536+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.536+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.644+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.645+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.728+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.729+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.730+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.758+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.763+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.833+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.834+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.834+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.903+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.904+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.958+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.959+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:18.960+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:18.990+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:18.990+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:19.009+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:19.040+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:19.043+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:19.117+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:19.118+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:19.358+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:19.390+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:19.390+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:19.477+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:19.478+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:19.812+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:19.849+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:19.917+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:19.983+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:19.986+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:20.275+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:20.276+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:20.288+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-30T23:05:20.399+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-30T23:05:20.402+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-10-30T23:05:20.402+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T23:05:20.403+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sensor_airflow.py", line 24, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:9092'], max_block_ms=5000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-30T23:05:20.515+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sensor_data, task_id=sensor_data_generator, run_id=scheduled__2024-10-30T23:00:00+00:00, execution_date=20241030T230000, start_date=20241030T230515, end_date=20241030T230520
[2024-10-30T23:05:20.627+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 62 for task sensor_data_generator (NoBrokersAvailable; 2137)
[2024-10-30T23:05:20.713+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-30T23:05:21.056+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T23:05:21.075+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
