[2024-11-24T01:45:01.039+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-24T01:45:01.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_data.fetch_data_from_api scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T01:45:01.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_data.fetch_data_from_api scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T01:45:01.429+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-24T01:45:02.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data_from_api> on 2024-11-23 00:00:00+00:00
[2024-11-24T01:45:02.276+0000] {standard_task_runner.py:64} INFO - Started process 273 to run task
[2024-11-24T01:45:02.281+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_data', 'fetch_data_from_api', 'scheduled__2024-11-23T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/***_producer.py', '--cfg-path', '/tmp/tmp404cma1r']
[2024-11-24T01:45:02.287+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask fetch_data_from_api
[2024-11-24T01:45:02.448+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_data.fetch_data_from_api scheduled__2024-11-23T00:00:00+00:00 [running]> on host 3e147e79ce3d
[2024-11-24T01:45:03.120+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bich Ly' AIRFLOW_CTX_DAG_ID='fetch_data' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T00:00:00+00:00'
[2024-11-24T01:45:03.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-24T01:45:03.237+0000] {logging_mixin.py:188} INFO - 1000
[2024-11-24T01:45:03.333+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: connecting to 10.0.2.15:9092 [('10.0.2.15', 9092) IPv4]
[2024-11-24T01:45:03.338+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: Connection complete.
[2024-11-24T01:45:09.546+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 0
[2024-11-24T01:45:09.550+0000] {airflow_producer.py:62} INFO - Offset: 0, Records fetched: 100
[2024-11-24T01:45:09.554+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: connecting to 10.0.2.15:9092 [('10.0.2.15', 9092) IPv4]
[2024-11-24T01:45:09.560+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: Connection complete.
[2024-11-24T01:45:09.560+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connected> [IPv4 ('10.0.2.15', 9092)]>: Closing connection. 
[2024-11-24T01:45:12.079+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:45:21.704+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 100
[2024-11-24T01:45:21.715+0000] {airflow_producer.py:62} INFO - Offset: 100, Records fetched: 100
[2024-11-24T01:45:22.836+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:45:30.844+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 200
[2024-11-24T01:45:30.850+0000] {airflow_producer.py:62} INFO - Offset: 200, Records fetched: 100
[2024-11-24T01:45:31.809+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:45:41.843+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 300
[2024-11-24T01:45:41.844+0000] {airflow_producer.py:62} INFO - Offset: 300, Records fetched: 100
[2024-11-24T01:45:42.463+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:45:52.080+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 400
[2024-11-24T01:45:52.100+0000] {airflow_producer.py:62} INFO - Offset: 400, Records fetched: 100
[2024-11-24T01:45:54.659+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:46:04.296+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 500
[2024-11-24T01:46:04.393+0000] {airflow_producer.py:62} INFO - Offset: 500, Records fetched: 100
[2024-11-24T01:46:09.953+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:46:20.689+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 600
[2024-11-24T01:46:21.154+0000] {airflow_producer.py:62} INFO - Offset: 600, Records fetched: 100
[2024-11-24T01:46:29.954+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:47:04.678+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 213, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/local_task_job_runner.py", line 261, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1821, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 510, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1807, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-24T01:47:05.512+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-24T01:47:07.331+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 700
[2024-11-24T01:47:07.481+0000] {airflow_producer.py:62} INFO - Offset: 700, Records fetched: 100
[2024-11-24T01:47:08.500+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:08.509+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:08.754+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:08.904+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:08.905+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:08.920+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.042+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.043+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.161+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:09.377+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.378+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.386+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:09.441+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.442+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.471+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.473+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.487+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.506+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.552+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:09.620+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.626+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.653+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.693+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.707+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:09.713+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.714+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.725+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.731+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.797+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.805+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.855+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:09.902+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.904+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.923+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.924+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.942+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.943+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.968+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.969+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:09.984+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:09.995+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:09.998+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.010+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.013+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.024+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.024+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.060+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.062+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.074+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.077+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.097+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.098+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.122+0000] {cluster.py:245} WARNING - No broker metadata found in MetadataResponse -- ignoring.
[2024-11-24T01:47:10.146+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.147+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.173+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.175+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.219+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.225+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.250+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.251+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:10.280+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('raw_data', 0) with base offset -1 log start offset None and error None.
[2024-11-24T01:47:10.292+0000] {record_accumulator.py:534} WARNING - [Error 6] NotLeaderForPartitionError
[2024-11-24T01:47:12.834+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:47:22.310+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 800
[2024-11-24T01:47:22.315+0000] {airflow_producer.py:62} INFO - Offset: 800, Records fetched: 100
[2024-11-24T01:47:23.231+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:47:33.588+0000] {airflow_producer.py:35} INFO - Fetched 100 records from API with offset 900
[2024-11-24T01:47:33.590+0000] {airflow_producer.py:62} INFO - Offset: 900, Records fetched: 100
[2024-11-24T01:47:34.048+0000] {airflow_producer.py:78} INFO - Streamed 100 records in this batch.
[2024-11-24T01:47:39.051+0000] {airflow_producer.py:89} INFO - Reached maximum offset or no more data; exiting.
[2024-11-24T01:47:39.051+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=10.0.2.15:9092 <connected> [IPv4 ('10.0.2.15', 9092)]>: Closing connection. 
[2024-11-24T01:47:39.053+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-24T01:47:39.054+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-24T01:47:39.063+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_data, task_id=fetch_data_from_api, run_id=scheduled__2024-11-23T00:00:00+00:00, execution_date=20241123T000000, start_date=20241124T014501, end_date=20241124T014739
[2024-11-24T01:47:39.089+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-24T01:47:39.111+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-24T01:47:39.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
